#!/usr/bin/env python
# -*- coding: utf-8 -*-


ROOT_WEATHER_API = 'opendata.cwb.gov.tw/api/v1/rest/datastore'
OBSERVATION_URI = 'O-A0003-001'
GROUP_OBSERVATIONS_URI = 'O-A0001-001'
STATION_URI = 'station'
FIND_OBSERVATIONS_URI = 'find'
FIND_STATION_URI = 'station/find'
BBOX_STATION_URI = 'box/station'
BBOX_CITY_URI = 'box/city'
THREE_HOURS_FORECAST_URI = 'F-C0032-001'
DAILY_FORECAST_URI = 'F-D0047-093'
STATION_WEATHER_HISTORY_URI = 'C-B0025-001'
ONE_CALL_URI = 'F-D0047-093'
ONE_CALL_HISTORICAL_URI = 'F-D0047-093'
ICONS_BASE_URI = ''
